---
- name: install common packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - sudo
    - ntp
    - ntpdate
    - crontabs
    - strace
    - less
    - vim-enhanced
    - lsof
    - tcpdump

- name: remove awful packages
  yum: name={{item}} state=absent update_cache=yes
  with_items:
    - NetworkManager
    - cups
    - iw
